#    Copyright (C) 2013 Alexandros Avdis and others.
#    See the AUTHORS file for a full list of copyright holders.
#
#    This file is part of qmesh.
#
#    qmesh is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    qmesh is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with qmesh.  If not, see <http://www.gnu.org/licenses/>.

# enable Docker
options:
  docker: true

definitions:
  caches:
    docker-dir-cache: /var/lib/docker/ 

pipelines:
  branches:
    master:
      - step:
          caches:
            # Cache directory where all docker images are stored.
            - docker-dir-cache
          script:
            - export QMESH_VERSION=`cat VERSION`
            - export IMAGE_NAME=qmesh/qmesh-containers:qmesh${QMESH_VERSION}_ubuntu20.04_qgisltr_gmsh3.0.6
            # Build container (install qmesh and test)
            - docker build -t $IMAGE_NAME ./tests/
            # authenticate with the Docker Hub registry
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            # push the new Docker image to the Docker registry
            - docker push $IMAGE_NAME
    CI/*:
      - step:
          caches:
            # Cache directory where all docker images are stored.
            - docker-dir-cache
          image: qmesh/qmesh-containers:ubuntu18.04_qgis3_gmsh3.0.4
          script:
            - pip3 install .
            - python3 setup.py test
      - step:
          caches:
            # Cache directory where all docker images are stored.
            - docker-dir-cache
          image: qmesh/qmesh-containers:ubuntu20.04_qgis3_gmsh3.0.6
          script:
            - pip3 install .
            - python3 setup.py test
  custom: #Custom pipelines are triggered manually
    test_on_ubuntu20.04_qgisltr_gmsh3.0.6:
      - step:
          caches:
            # Cache directory where all docker images are stored.
            - docker-dir-cache
          image: qmesh/qmesh-containers:ubuntu20.04_qgisltr_gmsh3.0.6
          script:
            - pip3 install .
            - python3 setup.py test
    deploy_on_pypi:
      - step:
          image: qmesh/qmesh-containers:ubuntu20.04_qgisltr_gmsh3.0.6
          script:
            # Upgrade pip
            - pip3 install --upgrade pip
            # install twine
            - sudo -H python3 -m pip install twine
            # Create a source distribution
            - python3 setup.py sdist
            # Upload to pypi
            - twine upload dist/*
